name: Tsunami
version: '${project.version}'
main: me.roxo.tsunami.Tsunami
api-version: 1.18
authors: [ Roxo ]
depend: [ProjectKorra]
tsunami.player:
  default: true
  children:
    bending.ability.Tsunami: true
